# Generated by Django 6.0.2 on 2026-03-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transactionentry',
            index=models.Index(fields=['account', 'created_at'], name='ledger_tran_account_011d78_idx'),
        ),
    ]
