# Generated by Django 6.0.2 on 2026-04-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_transactionentry_ledger_tran_account_011d78_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeraccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
