# Generated by Django 6.0.2 on 2026-04-16 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_ledgeraccount_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reverses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='ledger.transaction'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('reverses',), name='unique_reversal_per_transaction'),
        ),
    ]
