# Generated by Django 6.0.2 on 2026-04-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_auditlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='actions',
            new_name='action',
        ),
    ]
