# Generated by Django 6.0.2 on 2026-04-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_rename_actions_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='failed_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
