# Generated by Django 6.0.2 on 2026-04-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_transaction_failed_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PROCESSING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_id'], name='ledger_tran_referen_cfd32f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='ledger_tran_status_51b4c8_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionentry',
            index=models.Index(fields=['transaction'], name='ledger_tran_transac_be520c_idx'),
        ),
    ]
